# Generated by Django 5.0.3 on 2024-03-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('publisher_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('available_quantity', models.IntegerField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('class_dept', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
            ],
        ),
    ]
