# Generated by Django 5.0.3 on 2024-03-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='issue_return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('issued_date', models.DateField()),
                ('returned_date', models.DateField()),
                ('actual_returned_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='available_quantity',
            field=models.IntegerField(),
        ),
    ]
