# Generated by Django 5.0.3 on 2024-03-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_issue_return_alter_book_available_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='issue_return',
        ),
    ]
