# Generated by Django 5.0.3 on 2024-03-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_issue_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='issue_return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('expected_return_date', models.DateField()),
            ],
        ),
    ]
