# Generated by Django 5.0.3 on 2024-03-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_issue_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_return',
            name='return_date',
            field=models.DateField(default=None),
        ),
    ]
