# Generated by Django 5.0.3 on 2024-03-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_issue_return_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_return',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
