# Generated by Django 5.0.3 on 2024-03-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available_quantity',
        ),
    ]
